### ISSUE TITLE
StableDiffusionUI-Voldemort: SD Upscale Broken

### ISSUE THREAD

**Issue by Gushousekai195** [FuouM/HidamariDiffusionColab#3]
When I tried to use SD upscale on StableDiffusionUI-Voldemort, instead of working as intended, it gave me an error:

`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

It happens on both the gdrive and non-gdrive versions.

Please fix ASAP. This is the only colab that doesn't take forever to setup each time I want to use it.

**Comment by FuouM** [comment]
This colab itself doesn't support SD upscale (the code was from pre-sd upscale era from both optimized SD and hlky). As for the Voldemort SD I really have no idea. Personally I don't see any benefits in SD upscale and that would go against the "simple" nature of the colab.
